name: viddet-mx
channels:
  - conda-forge

dependencies:
  - python==3.6.3
  - pip
  - matplotlib
  - pip:
      - mxnet-cu102
      - gluoncv
      - gluonnlp
      - tensorflow-gpu
      - opencv-python
      - tqdm
      - requests
      - eventlet
      - lxml
      - Pillow
      - contextlib2
      - nltk
      - absl-py
      - tensorboardX
      - pyquery
      - decord